<header id="banner" class="wrapper">
  <div class="inner">
    <h2 id="banner-title">{{ page.subtitle }}</h2>
    <div id="banner-start">
        {{ page.description }}
    </div>
  </div>
</header>
<div id="content-wrap">
  <div class="wrapper">
    <div class="inner">
      {{ page.content }}
      <div id="intro-get-started-wrap">
        <a href="http://hanc.cc" target="_blank" id="intro-get-started-link">我的博客</a>
      </div>
    </div>
  </div>
</div>